"""Original PDF versus actual 3D: four monochrome comparisons, with SVG supplementary."""
import base64,html,json
from pathlib import Path
from PIL import Image
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A3,landscape
from reportlab.lib.utils import ImageReader
from reportlab.platypus import Paragraph
from reportlab.lib.styles import ParagraphStyle
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'audit/elevation-match'
PDF=ROOT/'output/pdf/9-glenn-four-face-comparison.pdf'
R=json.loads((OUT/'results.json').read_text());REF=json.loads((OUT/'pdf-reference.json').read_text())
ASSEMBLY=json.loads((ROOT/'assets/building-spec.json').read_text())['corniceAssembly']
LABELS={'front':'Front','rear':'Rear / back','left':'Left side','right':'Right side'}
FINDINGS={
 'front':[
  'Photo revision: four broad shallow-arched window openings replace the PDF pairs, retaining their outer set-outs. Raised surrounds run around the full openings.',
  'The front storey band now sits between the floors. Entrance bases are widened solids with returning steps; the garage front fascia is simpler, with a dark gutter.',
  'Upper arch piers now project 230 mm with returning eave caps and head bands, estimated from the supplied PDF side detail. Upper window details retain the PDF reconstruction. Arch rise, moulding dimensions and the hidden fourth-bay treatment remain inferred.',
  'These approved photo-based details intentionally differ from the PDF. Garage interior visibility and other unverified geometry remain visible differences.',
 ],
 'rear':[
  'Rear openings and trim remain based on the PDF, because no rear house photo was supplied.',
  'Scan skew, roof intersections, bay framing and the rear garage opening still differ; the plan shows a garage opening omitted from this elevation.',
 ],
 'left':[
  'Front porch bases now use the photographed stepped solid profile, visible in this side projection.',
  'Side and rear wall bands retain PDF levels; their transitions to the photo-based front storey band are unverified.',
  'Wall-return, frame and roof-cap linework still differ from the PDF.',
 ],
 'right':[
  'The stepped porch bases and front revised trim appear through their actual depth.',
  'Side and rear wall bands retain PDF levels; their transitions to the photo-based front storey band are unverified.',
  'Physical door frames, arch/jamb detail and visible lower garage geometry still differ from the PDF.',
 ],
}

def img(name):return 'data:image/png;base64,'+base64.b64encode((OUT/name).read_bytes()).decode()
def esc(s):return html.escape(str(s))
style='''*{box-sizing:border-box}body{margin:0;color:#111;background:#f8f8f6;font:15px/1.55 -apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}main{max-width:1600px;margin:auto;padding:42px 30px}h1{font-size:40px;line-height:1.15;letter-spacing:-1px;margin:10px 0 20px}h2{font-size:27px;margin:0}h3{font-size:18px}.eyebrow{letter-spacing:2px;text-transform:uppercase;font-size:11px;color:#555}.intro{max-width:1000px;font-size:18px}.notice{border:2px solid #111;background:white;padding:22px;margin:25px 0;max-width:1150px}.notice b{font-size:21px}nav{display:flex;overflow-x:auto;gap:25px;position:sticky;top:0;background:#f8f8f6f5;padding:14px 0;z-index:5;border-bottom:1px solid #aaa}a{color:inherit;text-underline-offset:4px}section{padding-top:30px;margin-top:45px;border-top:1px solid #aaa;scroll-margin-top:70px}.title{display:flex;justify-content:space-between;gap:20px;align-items:center}.badge{border:1px solid;padding:7px 12px;font-size:12px;white-space:nowrap}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:22px 0}figure{margin:0;background:white;padding:12px;border:1px solid #ddd}figcaption{font-size:12px;margin-bottom:10px;font-weight:600}img{display:block;width:100%}.controls{display:flex;gap:16px;align-items:center;margin:25px 0 10px}.controls input{flex:1;accent-color:black}button{padding:9px 14px;border:1px solid #777;background:white;cursor:pointer}.wipe{position:relative;overflow:hidden;border:1px solid #aaa;background:white}.wipe .reference{position:absolute;inset:0;clip-path:inset(0 calc(100% - var(--position)) 0 0)}.divider{position:absolute;left:var(--position);top:0;bottom:0;border-left:1px solid #777}.small{font-size:12px;color:#555;overflow-wrap:anywhere}ul{max-width:1150px}li{margin:8px 0}details{margin:20px 0}summary{cursor:pointer;font-weight:600}details figure{margin-top:15px}.method{max-width:1150px}table{border-collapse:collapse;width:100%;max-width:1150px;margin:25px 0}td,th{text-align:left;border-bottom:1px solid #ccc;padding:10px;font-size:13px}.links{display:flex;gap:24px;flex-wrap:wrap;margin:20px 0}@media(max-width:800px){main{padding:25px 16px}.pair{grid-template-columns:1fr}h1{font-size:30px}.title{align-items:start;flex-direction:column}.controls{flex-wrap:wrap}}'''
sections=[]
for r in R['views']:
 v=r['view'];label=LABELS[v];page=REF['registration'][v]['page']
 pdf=img(f'{v}-pdf-bw.png');model=img(f'{v}-model.png');svg=img(f'{v}-drawing.png')
 findings=''.join('<li>'+esc(x)+'</li>' for x in FINDINGS[v])
 sections.append(f'''<section id="{v}"><div class="title"><div><p class="eyebrow">Original PDF sheet {page} / elevation {r['drawing'].split('-')[-1]}</p><h2>{label}</h2></div><span class="badge">100% MATCH NOT ACHIEVED</span></div><div class="pair"><figure><figcaption>REFERENCE · Original PDF, black &amp; white</figcaption><img src="{pdf}" alt="Original PDF {label} elevation"></figure><figure><figcaption>ACTUAL 3D · Orthographic physical edges</figcaption><img src="{model}" alt="Updated model {label} elevation"></figure></div><div class="controls"><label>PDF / 3D comparison</label><input aria-label="{label} PDF model wipe" type="range" min="0" max="100" value="50"><button class="blink">Blink PDF / 3D</button></div><div class="wipe" style="--position:50%"><img src="{model}" alt="Model"><img class="reference" src="{pdf}" alt="Original PDF overlay"><span class="divider"></span></div><p class="small">Slider: PDF on the left, model on the right. Identical scale and datums; the PDF retains its original annotations and scan distortion.</p><ul>{findings}</ul><details><summary>Updated SVG elevation · supplementary output</summary><p>The SVG is updated from the cornice solids. It is not the reference used to judge the model.</p><figure><figcaption>{r['drawing']}.svg · current monochrome drawing</figcaption><img src="{svg}" alt="Updated SVG {label}"></figure><a href="../../drawings/{r['drawing']}.svg">Open editable SVG</a></details><details><summary>Raw difference image · includes scan and drafting differences</summary><figure><img src="{img(v+'-difference.png')}" alt="PDF model raw difference"></figure><p class="small">{r['differentPixels']:,} different pixels at 10 mm/pixel. Scan grain, line weights, labels, ground lines and opening symbols contribute. This count is not a measure of architectural accuracy.</p></details></section>''')
script="""for(const s of document.querySelectorAll('section')){const r=s.querySelector('input');if(!r)continue;const w=s.querySelector('.wipe'),b=s.querySelector('button');let timer;const set=v=>{r.value=v;w.style.setProperty('--position',v+'%')};r.oninput=()=>{clearInterval(timer);timer=null;b.textContent='Blink PDF / 3D';set(r.value)};b.onclick=()=>{if(timer){clearInterval(timer);timer=null;b.textContent='Blink PDF / 3D';return}let a=false;timer=setInterval(()=>{a=!a;set(a?100:0)},700);b.textContent='Stop blinking'}}"""
method='''<p><b>PDF comparison reference:</b> original <i>003 - 9 Glenn street.pdf</i>, sheets 5 and 6, freshly rendered at 216 dpi. It remains the comparison reference, while the approved front revision uses the house photos for visible trim shape. The full rendered source pages and source SHA-256 are retained beside this report.</p><p><b>Registration:</b> a fixed translation and X/Y scale from the plan spans and the printed 6,041 mm upper-ceiling-to-ground-floor height. No fitting to model edges, perspective correction or local warping. Small scan skew remains visible. All output views use 10 mm per pixel and the same fixed bounds for PDF and 3D.</p><p><b>3D:</b> actual meshes rendered with level orthographic cameras. Black lines are silhouettes, creases and depth changes. Colours, textures and shadows are removed; glass is opaque for the edge pass. Cellar geometry and the photo-based landscaping are hidden. No PDF or SVG linework is pasted onto the model.</p><p><b>What changed:</b> four combined shallow-arched front windows with solid surrounds, a front band between the storeys, widened stepped porch bases and a plain garage front fascia with dark gutter. The two upper piers now project 230 mm, with returning caps and head bands and an extended gable roof above. Upper sill bands and rear trim remain. Corners follow the plan setbacks. The SVGs now use visible projections of these same solids, replacing separately drawn band profiles.</p><p><b>Limits:</b> the PDF labels band heights in brick courses but does not dimension the moulding depth. The 180 mm shallow arch rise, 220 mm surround width, 55 mm projection, other moulding steps and 230 mm upper-pier relief are inferred. The scan also includes paper grain, drawing symbols, level lines and notes which are not physical 3D edges. No four-face 100% match is claimed; these images expose remaining differences for review.</p>'''
def photo_img(name):
 return 'data:image/png;base64,'+base64.b64encode((ROOT/'audit/photo-reference'/name).read_bytes()).decode()
photo_section=f'''<section id="photos"><h2>Photographed appearance</h2><p>The front is revised from these photographs. Perspective and foliage prevent an exact dimensional comparison. The fourth front window group repeats the visible treatment as an inference.</p><div class="pair"><figure><figcaption>House photograph · windows and horizontal band</figcaption><img src="{photo_img('windows-close.png')}" alt="Actual house window surrounds"></figure><figure><figcaption>Updated 3D front · physical edges</figcaption><img src="{img('front-model.png')}" alt="Revised front model"></figure></div><div class="pair"><figure><figcaption>House photograph · stepped entrance bases</figcaption><img src="{photo_img('entrance-close.png')}" alt="Entrance base detail"></figure><figure><figcaption>House photograph · plain garage fascia and dark gutter</figcaption><img src="{photo_img('garage-close.png')}" alt="Garage fascia detail"></figure></div><p><b>Inferred dimensions:</b> 180 mm arch rise, 220 mm surround width, 55 mm surround projection. Combined openings retain the outer extents of the PDF window pairs. Upper-window details and elevations not shown in the photos retain their PDF reconstruction.</p></section>'''
colour_section=f'''<h3>Photo-matched exterior colours</h3><p>Warm ivory render and lighter cream-white trim, charcoal roof tiles and frames, dark brown timber entrance leaves, and a terracotta porch finish. These are visual approximations from the supplied photographs under neutral daylight; they are not measured paint specifications. Transparent glazing is retained.</p><div class="pair"><figure><figcaption>Actual house · colour reference</figcaption><img src="{photo_img('actual-house-front.png')}" alt="Actual house colour reference"></figure><figure><figcaption>Updated 3D · colour front view</figcaption><img src="{photo_img('model-colour-front.png')}" alt="Photo-matched model colours"></figure></div><div class="pair"><figure><figcaption>Supplied PDF side detail · upper pier projection</figcaption><img style="max-height:480px;object-fit:contain" src="{photo_img('upper-pier-side-detail.png')}" alt="Upper pier side detail supplied by the user"></figure><figure><figcaption>Actual 3D · two upper shafts, caps and returning bands</figcaption><img src="{photo_img('model-upper-piers.png')}" alt="Close view of the modelled upper piers"></figure></div><p>The previous 30 mm applied relief is replaced by an estimated 230 mm projection. Both 590 mm wide shafts run from the portico roof level to the upper eave caps. Stepped caps and head bands return around their sides; the gable roof covers the deeper caps. SVG elevations are regenerated from the same solids. The side drawing establishes the form, but gives no written depth dimension.</p>'''
photo_section=photo_section.replace('</section>',colour_section+'</section>')
page=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>9 Glenn · Original PDF vs 3D</title><style>{style}</style><main><p class="eyebrow">9 Glenn / original PDF reference</p><h1>Front trim updated from the house photos.<br>PDF differences remain visible.</h1><p class="intro">The front now incorporates photo-matched exterior colours, deeper upper piers, window surrounds, storey band, porch bases and garage fascia. The four-view comparison below still uses the original PDF on the left and actual 3D geometry on the right. Updated SVGs are supplementary outputs.</p><div class="notice"><b>100% match: not achieved.</b><br>The approved front details intentionally differ from the PDF. Photos control visible trim shape; PDF set-outs control nominal position and width. Depths, arch rise and hidden details remain inferred.</div><div class="links"><a href="../../output/pdf/9-glenn-four-face-comparison.pdf">Download comparison report</a><a href="../../9-glenn-viewer.html#3d">Open updated 3D model</a><a href="../pool/comparison.html">Pool and fountain photo comparison</a><a href="../landscape/comparison.html">Driveway and planting photo comparison</a><a href="original-pdf-sheet-5.png">Original sheet 5</a><a href="original-pdf-sheet-6.png">Original sheet 6</a></div><nav><a href="#photos">House photos</a><a href="#front">Front</a><a href="#rear">Rear</a><a href="#left">Left side</a><a href="#right">Right side</a><a href="#method">Method</a></nav>{photo_section}{''.join(sections)}<section class="method" id="method"><h2>Source and comparison method</h2>{method}<p class="small">Source SHA-256: {REF['sha256']}<br>{len(ASSEMBLY['bands'])} band runs / {len(ASSEMBLY['faces'])} solid faces. Reproduce with npm run audit:elevations.</p></section></main><script>{script}</script></html>'''
(OUT/'comparison.html').write_text(page)
# Portable report: one overview, followed by a large stacked comparison per face.
PDF.parent.mkdir(parents=True,exist_ok=True);c=canvas.Canvas(str(PDF),pagesize=landscape(A3));W,H=landscape(A3);M=40
pstyle=ParagraphStyle('body',fontName='Helvetica',fontSize=11,leading=16)
def para(text,y,w=None):
 p=Paragraph(text,pstyle);_,h=p.wrap(w or W-2*M,H);p.drawOn(c,M,y-h);return y-h

def heading(title,sub):
 c.setFont('Helvetica',10);c.drawString(M,H-32,'9 GLENN / ORIGINAL PDF VS ACTUAL 3D');c.setFont('Helvetica-Bold',25);c.drawString(M,H-70,title);return para(sub,H-87)
def footer(n):
 c.setFont('Helvetica',8);c.drawString(M,20,'Original PDF sheets 5-6 | Black and white | 100% match not achieved');c.drawRightString(W-M,20,f'{n} / 5');c.showPage()
def picture(name,y,maxh):
 im=Image.open(OUT/name);scale=min((W-2*M)/im.width,maxh/im.height);dw,dh=im.width*scale,im.height*scale;c.drawImage(ImageReader(im),(W-dw)/2,y-dh,dw,dh);return y-dh
heading('Photo-based front trim; PDF comparison','Approved front details now follow the house photos. The original PDF remains the comparison reference; no 100% match is claimed.')
y=H-155
for title,text in [('Added to 3D and SVG','Four combined shallow-arched front windows with projecting surrounds; a front band between floors; solid stepped porch bases; simpler garage fascia and dark gutter. Upper piers now project an estimated 230 mm, with returning stepped bands and roof coverage. Exterior colours approximate the photos; the HTML includes colour renders.'),('Real depth and corner returns','Bands follow the registered X/Z setbacks and wrap corners as solid profiles. The front arch surrounds remain clear. SVG bands are projections of the same physical faces.'),('PDF reference','Original 003 - 9 Glenn street.pdf, sheets 5 and 6, freshly rendered at 216 dpi. Fixed scale and datums from printed dimensions; no fitting to the model and no local warping.'),('Reading the comparisons','Each following page shows the original PDF above the actual 3D elevation at the same scale. Annotations, paper grain, pen weight and scan skew are retained. These are visual comparisons, not architectural certification.'),('Remaining limits','Roof cap/junction detail, glazing, exposed wall returns and ground/interior visibility still differ. Arch rise of 180 mm, surround width of 220 mm and projection of 55 mm are inferred. The fourth-bay treatment repeats the visible motif. Front changes intentionally differ from the PDF. The interactive HTML also includes the updated SVGs and a PDF/model wipe slider.')]:
 c.setFont('Helvetica-Bold',14);c.drawString(M,y,title);y=para(text,y-14)-30
para('Source SHA-256: '+REF['sha256'],y)
footer(1)
for i,r in enumerate(R['views'],2):
 v=r['view'];y=heading(LABELS[v],f'Original PDF sheet {REF["registration"][v]["page"]} / {r["drawing"]} | Fixed registration | 100% match not achieved')-20
 maxh=245
 for label,name in [('REFERENCE - Original PDF',v+'-pdf-bw.png'),('ACTUAL 3D - Physical edges, cornice bands included',v+'-model.png')]:
  c.setFont('Helvetica-Bold',10);c.drawString(M,y,label);y=picture(name,y-8,maxh)-20
 for finding in FINDINGS[v]:y=para('- '+finding,y)-5
 footer(i)
c.save();print('Wrote original-PDF comparison HTML and five-page PDF report.')
