const assert = require('node:assert/strict');
const { chromium } = require('/Users/yinsee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = process.env.VIEWER_BASE_URL || 'http://127.0.0.1:8148/';
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome', ignoreDefaultArgs: ['--enable-unsafe-swiftshader'], args: ['--enable-unsafe-webgpu', '--disable-frame-rate-limit'] });
  try {
    const shell = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    await shell.route(/\.js(?:\?.*)?$/, route => route.abort());
    await shell.goto(base);
    assert.equal(new URL(shell.url()).hash, '#compare/ground');
    assert.equal(await shell.locator('#triple-view').isVisible(), true);
    assert.equal(await shell.locator('#mode-2d, .header-meta, .sidebar-footer').count(), 0);
    assert.equal(await shell.locator('[data-compare-pane]:visible').count(), 3);
    assert.equal(await shell.locator('.app-header').evaluate(el => el.getBoundingClientRect().height), 50);
    assert.equal(await shell.locator('.main > .toolbar').isVisible(), false);
    await shell.screenshot({ path: 'tmp/startup-before-scripts.png' });
    await shell.setViewportSize({ width: 390, height: 844 });
    assert.equal(await shell.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await shell.close();

    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    let release, requests = 0;
    const held = new Promise(resolve => { release = resolve; });
    await page.route('**/assets/model-3d.js*', async route => { requests++; await held; await route.continue(); });
    await page.goto(base, { waitUntil: 'domcontentloaded' });
    await page.waitForSelector('#triple-loading', { state: 'visible' });
    await page.click('#mode-3d');
    await page.waitForSelector('#model-loading', { state: 'visible' });
    release();
    await page.waitForFunction(() => Boolean(window.Building3D?.instance));
    await page.waitForSelector('#model-loading', { state: 'hidden' });
    assert.equal(await page.evaluate(() => Boolean(window.TripleView?.instance)), false);
    await page.click('#mode-compare');
    await page.waitForFunction(() => Boolean(window.TripleView?.instance?.drawing));
    await page.waitForSelector('#triple-loading', { state: 'hidden' });
    assert.equal(requests, 1);
    await page.selectOption('#triple-drawing', 'first');
    await page.waitForFunction(() => TripleView.instance.drawing.id === 'first');
    assert.equal(await page.locator('.triple-panes figure:visible').count(), 3);
    assert.deepEqual(errors, []);
    await page.screenshot({ path: 'tmp/startup-ready.png' });
    await page.close();

    const retry = await browser.newPage();
    let attempts = 0;
    await retry.route('**/assets/model-3d.js*', route => ++attempts === 1 ? route.abort() : route.continue());
    await retry.goto(base + '#3d');
    await retry.waitForSelector('#model-loading button', { state: 'visible' });
    await retry.click('#model-loading button');
    await retry.waitForSelector('#model-loading', { state: 'hidden' });
    assert.equal(attempts, 2);
    assert.equal(await retry.evaluate(() => Building3D.instance.renderer.backend.isWebGPUBackend), true);
    await retry.click('#model-tour');
    await retry.waitForSelector('body.mode-tour #tour-hud', { state: 'visible' });
    await retry.keyboard.press('Escape');
    await retry.click('#tour-exit');
    await retry.waitForFunction(() => !document.body.classList.contains('mode-tour'));
    await retry.close();
    console.log('PASS static first paint, default Compare, mobile startup, navigation during loading, single download, drawing selection, retry and tour exit');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
